# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
#  pull_request:
#   branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v1.4.0
      with:
        # SDK version to use. Example: 2.2.104
        dotnet-version: '3.1.100'

    - name: install unity packer
      run: dotnet tool install -g unity-packer

    - name: Create Package
      run: unity-packer pack LiteNetLib4Mirror.unitypackage LiteNetLib4Mirror/Assets/Mirror/Runtime/Transport Assets/Mirror/Runtime/Transport
      
    - name: Upload Package
      uses: actions/upload-artifact@v1
      with:
        name: LiteNetLib4Mirror.unitypackage
        path: LiteNetLib4Mirror.unitypackage

    - name: Action For Semantic Release
      uses: cycjimmy/semantic-release-action@v2.3.0
      with:
        # The branch on which releases should happen. It will override the branch attribute in your configuration file. If the attribute is not configured on both sides, the default is master. Support for semantic-release older than v16.
        branch: master
      env: 
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

